version: 1.0.{build}

image: Visual Studio 2017

platform: 
 - x86
 - x64

configuration:
 - Debug

clone_folder: c:\ffmpeg

build_script:
 - cd 3rdParty
 - cd FFMpeg
 - C:\msys64\usr\bin\bash -lc "./configure --toolchain=msvc"
 - make
 - make install

test: off